version: '3'

services:
  nginx-rtmp:
    image: vallahaye/nginx-rtmp:stable-alpine
    container_name: nginx-rtmp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./videojs.html:/mnt/videojs.html
      - ./hlsjs.html:/mnt/hlsjs.html
    ports:
      - "1935:1935"
      - "8080:8080"
